modLoader = "javafml"
loaderVersion = "[40,)"
license = "GPL-3.0"
issueTrackerURL = "https://github.com/enjarai/do-a-barrel-roll/issues" #optional

[[mods]]
modId = "do_a_barrel_roll"
version = "${version}"
displayName = "Do A Barrel Roll"
authors = "enjarai"
modUrl = "https://github.com/enjarai/do-a-barrel-roll" #optional

logoFile="icon.png"
description = '''
Microsoft flight simulator for Minecraft elytras.

Big thanks to MehVahdJukaar (https://github.com/MehVahdJukaar) for their help with the Forge port.
'''

[[dependencies.do-a-barrel-roll]]
modId = "forge"
mandatory = true
versionRange = "[42.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.do-a-barrel-roll]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

