modLoader = "javafml"
loaderVersion = "[40,)"
license = "GPL-3.0"
issueTrackerURL = "https://github.com/enjarai/do-a-barrel-roll/issues" #optional

[[mods]]
modId = "doabarrelroll"
version = "${version}"
displayName = "Do A Barrel Roll"
authors = "enjarai"
modUrl = "https://github.com/enjarai/do-a-barrel-roll" #optional

logoFile="assets/do-a-barrel-roll/icon.png"
description = '''
Microsoft flight simulator for Minecraft elytras.
'''

[[dependencies.do-a-barrel-roll]]
modId = "forge"
mandatory = true
versionRange = "[42.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.do-a-barrel-roll]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

