name: Publish

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      game_vers:
        required: true
        type: string
      java_vers:
        required: true
        type: string
      GITHUB_REF:
        required: true
        type: string
    secrets:
      CURSEFORGE_TOKEN:
        required: true
      MODRINTH_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ inputs.java_vers }}

      - name: Grant Execute Permiussion
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build

      - name: Publish to Maven
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_enjaraiMavenUsername: ${{ secrets.PUBLISH_MAVEN_USERNAME }}
          ORG_GRADLE_PROJECT_enjaraiMavenPassword: ${{ secrets.PUBLISH_MAVEN_PASSWORD }}

      - name: Upload To Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.branch }}
          path: ./build/libs/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.branch }}

      - name: Check For Fabric Jar
        uses: actions/github-script@v5
        id: fabric_release
        with:
          result-encoding: string
          script: |
            const fs = require("fs")
            return fs.readdirSync("./").filter(e => !e.endsWith("dev.jar") && !e.endsWith("sources.jar") && !e.endsWith("shadow.jar") && e.endsWith(".jar") && e.includes("fabric"))[0] || false;

      - name: Check For Forge Jar
        uses: actions/github-script@v5
        id: forge_release
        with:
          result-encoding: string
          script: |
            const fs = require("fs")
            return fs.readdirSync("./").filter(e => !e.endsWith("dev.jar") && !e.endsWith("sources.jar") && !e.endsWith("shadow.jar") && e.endsWith(".jar") && e.includes("forge"))[0] || false;

      - name: Extract Mod Version
        uses: actions/github-script@v5
        id: mod_version
        env:
          REF: '${{ inputs.GITHUB_REF }}'
        with:
          result-encoding: string
          script: |
            return process.env.REF.replace(/\/?refs\/tags\//, '')
      - name: Extract Game Version
        uses: actions/github-script@v5
        id: game_version
        env:
          GV: '${{ inputs.game_vers }}'
        with:
          result-encoding: string
          script: |
            return process.env.GV.split(/\s/)[0]

      - name: Run Publish Forge
        if: ${{ steps.forge_release.outputs.result != 'false' }}
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: 6FtRfnLg
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          #          dependencies: ""
          curseforge-id: 663658
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}

          name: '${{ steps.mod_version.outputs.result }} for Forge ${{ steps.game_version.outputs.result }}'
          version: '${{ steps.mod_version.outputs.result }}+${{ steps.game_version.outputs.result }}-forge'

          files: ./${{ steps.forge_release.outputs.result }}
          version-type: release

          loaders: forge
          game-versions: ${{ inputs.game_vers }}

          modrinth-featured: false
          changelog-file: CHANGELOG.md

          java: ${{ inputs.java_vers }}
          retry-attempts: 5
          retry-delay: 60000

      - name: Run Publish Fabric
        if: ${{ steps.fabric_release.outputs.result != 'false' }}
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: 6FtRfnLg
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          dependencies: |
            fabric-api | depends | *
          curseforge-id: 663658
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}

          name: '${{ steps.mod_version.outputs.result }} for Fabric ${{ steps.game_version.outputs.result }}'
          version: '${{ steps.mod_version.outputs.result }}+${{ steps.game_version.outputs.result }}-fabric'

          files: ./${{ steps.fabric_release.outputs.result }}
          version-type: release

          loaders: fabric
          game-versions: ${{ inputs.game_vers }}

          modrinth-featured: false
          changelog-file: CHANGELOG.md

          java: ${{ inputs.java_vers }}
          retry-attempts: 5
          retry-delay: 60000

