name: Publish All

on:
  release:
    types: [ created ]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: Update GitHub Release
        uses: tubone24/update_release@v1.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: CHANGELOG.md
          is_append_body: true

  deploy_1_19_4:
    uses: enjarai/do-a-barrel-roll/.github/workflows/publish.yml@1.19.4/next
    with:
      branch: 1.19.4/next
      game_vers: |
        1.19.4
      java_vers: 17
      GITHUB_REF: ${{ github.ref }}
    secrets:
      CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      PUBLISH_MAVEN_USERNAME: ${{ secrets.PUBLISH_MAVEN_USERNAME }}
      PUBLISH_MAVEN_PASSWORD: ${{ secrets.PUBLISH_MAVEN_PASSWORD }}

  deploy_1_20:
    needs: deploy_1_19_4
    uses: enjarai/do-a-barrel-roll/.github/workflows/publish.yml@1.20/dev
    with:
      branch: 1.20/dev
      game_vers: |
        1.20
      java_vers: 17
      GITHUB_REF: ${{ github.ref }}
    secrets:
      CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      PUBLISH_MAVEN_USERNAME: ${{ secrets.PUBLISH_MAVEN_USERNAME }}
      PUBLISH_MAVEN_PASSWORD: ${{ secrets.PUBLISH_MAVEN_PASSWORD }}
