name: Build Release

on:
  release:
    types: [ created ]

jobs:
  build:
    uses: enjarai/do-a-barrel-roll/.github/workflows/build_all.yml@main

  deploy_1_19:
    uses: enjarai/do-a-barrel-roll/.github/workflows/publish.yml@main
    with:
      branch: main
      game_vers: |
        1.19
        1.19.1
        1.19.2
      java_vers: 17
      GITHUB_REF: ${{ github.ref }}
    secrets:
      CF_API_KEY: ${{ secrets.CURSEFORGE_TOKEN }}
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
    needs:
      - build
      - deploy_1_18

  deploy_1_18:
    uses: enjarai/do-a-barrel-roll/.github/workflows/publish.yml@1.18.2
    with:
      branch: 1.18.2
      game_vers: 1.18.2
      java_vers: 17
      GITHUB_REF: ${{ github.ref }}
    secrets:
      CF_API_KEY: ${{ secrets.CURSEFORGE_TOKEN }}
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
    needs:
      - build
